import { CreateModal, FindModal } from "@/components/Modal";
import Providers from "@/providers";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="pt-BR" data-theme="luxury">
            <Providers>
                <body className="w-full h-full bg-base-100 tracking-wider overflow-hidden">
                    <div className="w-full h-full">{children}</div>
                    <FindModal />
                    <CreateModal />
                </body>
            </Providers>
        </html>
    );
}
