import { Footer } from "@/components/Footer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="pt-BR" data-theme="luxury">
            <body className="w-screen h-screen bg-base-100 tracking-wider">
                <div className="w-full h-full pb-16">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
